# Default values for dibbs-desktop.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

resourcePrefix: dibbs-user

# Specify number of replicas (should be one for non-HA deployment)
replicaCount: 1

image:
  # Specify docker image repository
  repository: abf123
  # Specify docker image name
  name: dibbs-psu
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "desktop-ubuntu"

ingress:
  hostSuffix: apps.dibbs-okd.cloud.icds.psu.edu

service:
  port: 80
  protocol: TCP
  name: http

container:
  port: 8080
  env:
    - name: CHOWN_HOME
      value: 'yes'
    - name: CHOWN_HOME_OPTS
      value: '-R'
  mountPath: /home/dibbs-user