{{ $token := randAlphaNum 64 }}
---
# Store JupyterLab token as a secret
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-configmap"
data:
  token: "{{ $token }}"
  test: "{{ $testing }}"
---
# Jupyterlab deployment for standard Jupyter docker container
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-deployment"
  labels:
    name: "{{ .Release.Name }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: "{{ .Release.Name }}"
  template:
    metadata:
      labels:
        name: "{{ .Release.Name }}"
    spec:
      securityContext:
        fsGroup: 100
      serviceAccount: sa-with-anyuid
      serviceAccountName: sa-with-anyuid
      containers:
        - name: "{{ .Release.Name }}-container"
          image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          env:
            {{- toYaml .Values.container.env | nindent 12 }}
          ports:
          - containerPort: {{ .Values.container.port }}
          command:
            - /bin/bash
            - -c
            - |
              start.sh jupyter lab --ServerApp.token={{ $token | quote }} \
                --ServerApp.password='' --debug --ServerApp.ip='0.0.0.0' --ServerApp.allow_remote_access='True' --ServerApp.allow_origin='*' \
                --LabApp.allow_remote_access='True' --LabApp.allow_origin='*' --ServerApp.disable_check_xsrf='True'
          volumeMounts:
            - name: "{{ .Values.resourcePrefix }}-{{ .Values.username }}-data"
              mountPath: "{{ .Values.container.mountPath }}"
          resources:
            requests:
              memory: 4Gi
              cpu: 1000m
          securityContext:
            runAsUser: 1000
            runAsGroup: 100
      restartPolicy: Always
      volumes:
      - name: "{{ .Values.resourcePrefix }}-{{ .Values.username }}-data"
        persistentVolumeClaim:
          claimName: "{{ .Values.resourcePrefix }}-{{ .Values.username }}-pvc"