{{ $token := randAlphaNum 64 }}
{{ $ingressPrefix := randAlphaNum 8 | lower}}
---
# Store JupyterLab token as a secret
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-configmap"
data:
  token: "{{ $token }}"
  ingressPrefix: "{{ $ingressPrefix }}"